### ISSUE TITLE
There aren’t any releases? [INFO]

### ISSUE THREAD

**Issue by kzorluoglu** [PineCSS/pine#6]
You has new version announced,but havent any  [relases](https://github.com/PineCSS/pine/releases) on github ?

For new release announce (Turkish);  

- Http://rogerdudler.github.io/git-guide/index.tr.html -> sürümlemek
- https://git-scm.com/book/tr/v1/Git-in-Temelleri-Etiketleme

**Comment by saltun** [comment]
Teşekkürler sürümleme bilgisi eklendi.
